:: Author: Mouad ZAID - CC\EYB5
:: Automate comment filling in the 
:: measurement files generated by MM6x

:Variables
SET fileMeasurementPath=C:\mt\13092021\MeasurementBrut\
SET CSVfilename=C:\mt\EM\LDM\GolfGTE_ECU_WO_XPC\temp\_extract\tables\internals.csv

:findString
SET CSVfilename=C:\mt\EM\LDM\GolfGTE_ECU_WO_XPC\temp\_extract\tables\internals.csv
CD C:\mt\EM\LDM\GolfGTE_ECU_WO_XPC\temp\_extract\tables\

for /f "tokens=*" %%i in ('FINDSTR /C:"Node" %CSVfilename%') do set var1=%%i  
echo %var1:~5,10%
SET var1=%var1:~5,10%

for /f "tokens=*" %%j in ('FINDSTR /C:"Device" %CSVfilename%') do set var2=%%j 
echo %var2:~15,16%
SET var2=%var2:~15,16%

for /f "tokens=*" %%k in ('FINDSTR /C:"TFW_Version" %CSVfilename%') do set var3=%%k
echo %var3:~12,14%
SET var3=%var3:~12,14%

for /f "tokens=*" %%m in ('FINDSTR /C:"FileName" %CSVfilename%') do set var5=%%m
echo %var5:~12,15%
SET var5=%var5:~12,15%

for /f "tokens=*" %%n in ('FINDSTR /C:"ProjectFolder" %CSVfilename%') do set var6=%%n
echo %var6:~14,57%
SET var6=%var6:~14,57%

for /f "tokens=*" %%n in ('FINDSTR /C:"ImcCom_Version" %CSVfilename%') do set var7=%%n
echo %var7:~15,12%
SET var7=%var7:~15,12%

set datetime=%date:~-4,4%%date:~-10,2%%date:~-7,2%_%time:~0,2%%time:~3,2%%time:~6,2%

::GOTO fillString

for %%f in (%fileMeasurementPath%*) do (
set ZipDir=%%~nf
PAUSE
if not exist "C:\mt\13092021\Tempo\%%~nf\" mkdir C:\mt\13092021\Tempo\%%~nf
copy "%%f" "C:\mt\13092021\Tempo\%%~nf\"
7z x C:\mt\13092021\Tempo\%%~nf\ -Y -oC:\mt\13092021\Tempo\%%~nf\
cd C:\mt\13092021\Tempo\%%~nf\
del /S *.ZIP
::GOTO findString
:fillString
(
echo Release Date : %datetime% 
echo File Name : %%~nf
echo User: %USERNAME%
echo PC Name: %var1%
echo IMCDev Version: %var2%
echo IMCCom Version: %var7%
echo TFW Version: %var3%
echo Project Path: %var6%
echo .
echo __________________ADDITIONAL_COMMENT___ROBERT_BOSCH_GMBH______________________
echo    NAME        : PSA 
echo    CAR         : PSA EMP2V4
echo    NUMBER      : CTP#02    
echo    BRAKES      : Hitachi Brakes O48 360x26, MoC Left nø22024200005304 and MoC Right MoC nø22024200004904
echo    TESTENGINEER: 
echo    PLACE       : Dy / EYB5
echo    SYSTEM      : ESP9.3 HP / APB-Mi B-sample
echo    ECU         : 99 00012 / 0273B71795
echo    SOFTWARE    : ApplContainer_V0200_BB81940_CSWxBxD5EDxEMP2V4xHP.appl.zip / HP Janv 2021
echo    HU          : 0 265 B49 554-03 / CC-222674
echo    SENSORS     : ACEK07, ACEK09, ACPE080, ACPE075, ACPE070, ACPE056, ADIL20, ADIL26, ADIL40
echo ______________________________________________________________________________________
)>C:\mt\13092021\Tempo\%%~nf\output.txt 
7z a -tzip "C:\mt\13092021\MeasurementRework\%%~nf" "C:\mt\13092021\Tempo\%%~nf\*" -v2k
)



